# Numpy

### numpy functions_1

In [50]:
# 문1
import numpy as np
a = np.zeros(10)
a

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [51]:
# 문2
import numpy as np
a = np.zeros(10)
a[4] = 1
a

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [52]:
# 문3
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [53]:
# 문4
np.arange(0,25).reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
# 문5
np.eye((5))

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### numpy functions_2

In [55]:
a = np.random.rand(5,5)
print(a)
min = a[0][0]
max = a[0][0]
for i in range(5):
    for j in range(5):
        if min >= a[i][j]:
            min = a[i][j]
        if max <= a[i][j]:
            max = a[i][j]
print(min, max)

[[ 0.98133448  0.86672395  0.93073438  0.50278847  0.79558995]
 [ 0.8823494   0.86675461  0.14491662  0.63536469  0.7470937 ]
 [ 0.95907925  0.99106147  0.34930601  0.53748244  0.54943171]
 [ 0.97173685  0.14289906  0.7842488   0.5258306   0.99150669]
 [ 0.57288176  0.04713485  0.71830846  0.41900074  0.04468101]]
0.0446810136108 0.991506687448


In [56]:
a = np.ones((4,3))
print(a)
print()
b = np.random.rand(3,2)
print(b)
print()
c = np.dot(a,b)
print(c)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[ 0.93918799  0.42535299]
 [ 0.95206364  0.02656278]
 [ 0.32029425  0.08899262]]

[[ 2.21154588  0.5409084 ]
 [ 2.21154588  0.5409084 ]
 [ 2.21154588  0.5409084 ]
 [ 2.21154588  0.5409084 ]]


In [57]:
c.transpose()

array([[ 2.21154588,  2.21154588,  2.21154588,  2.21154588],
       [ 0.5409084 ,  0.5409084 ,  0.5409084 ,  0.5409084 ]])

In [58]:
a = np.arange(0,25)
b = np.arange(25,50)
print(a)
print(b)
print()
print(a+b)
print(a-b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73]
[-25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25
 -25 -25 -25 -25 -25 -25 -25]


# Pandas

기본 데이터

In [59]:
import pandas as pd
import numpy as np

In [60]:
exam_data = {'name': ['Anastasia', 'Catherine', 'Cahill', 'James', 'Emily', 'Michael', 'Monica', 'Laura', 'Kevin', 'Jordan'],
            'score': [13, 9.5, 16.5, np.nan, 11, 20, 17, np.nan, 8.5, 19],
            'attempts': [1, 3, 3, 2, 2, 3, 2, 3, 2, 1],
            'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(exam_data, index=labels)
df

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
d         2      James      no    NaN
e         2      Emily      no   11.0
f         3    Michael     yes   20.0
g         2     Monica     yes   17.0
h         3      Laura      no    NaN
i         2      Kevin      no    8.5
j         1     Jordan     yes   19.0

[1-1]

In [64]:
df_0101 = df[['name','score']]
df_0101

name  score
a  Anastasia   13.0
b  Catherine    9.5
c     Cahill   16.5
d      James    NaN
e      Emily   11.0
f    Michael   20.0
g     Monica   17.0
h      Laura    NaN
i      Kevin    8.5
j     Jordan   19.0

[1-2]

In [65]:
df_0102 = df.iloc[:3]
df_0102

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5

[1-3]

In [66]:
df_0103 = df.iloc[[0,1,4,5],[1,3]]
df_0103

name  score
a  Anastasia   13.0
b  Catherine    9.5
e      Emily   11.0
f    Michael   20.0

[1-4]

In [67]:
df_0104 = df[df['attempts'] > 2]
df_0104

attempts       name qualify  score
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
f         3    Michael     yes   20.0
h         3      Laura      no    NaN

[2-1]

In [68]:
df_0201 = df[pd.isnull(df['score'])==True]
df_0201

attempts   name qualify  score
d         2  James      no    NaN
h         3  Laura      no    NaN

[2-2]

In [70]:
df_0202 = df[(df['attempts']<2) & (df['score']>15)]
df_0202

attempts    name qualify  score
j         1  Jordan     yes   19.0

[2-3]

In [71]:
df_0203 = df['attempts'].sum()
df_0203

22

[2-4]

In [72]:
df_0204 = df['score'].mean()
df_0204

14.3125

[3-1]

In [73]:
df_0301 = df.copy()
df_0301.loc['k'] = [2,"Saya","yes",17.5]
df_0301

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
d         2      James      no    NaN
e         2      Emily      no   11.0
f         3    Michael     yes   20.0
g         2     Monica     yes   17.0
h         3      Laura      no    NaN
i         2      Kevin      no    8.5
j         1     Jordan     yes   19.0
k         2       Saya     yes   17.5

[3-2]

In [74]:
df_0302 = df_0301.drop('k')
df_0302

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
d         2      James      no    NaN
e         2      Emily      no   11.0
f         3    Michael     yes   20.0
g         2     Monica     yes   17.0
h         3      Laura      no    NaN
i         2      Kevin      no    8.5
j         1     Jordan     yes   19.0

[3-3]

In [75]:
df_0303 = df.drop('attempts', axis=1)
df_0303

name qualify  score
a  Anastasia     yes   13.0
b  Catherine      no    9.5
c     Cahill     yes   16.5
d      James      no    NaN
e      Emily      no   11.0
f    Michael     yes   20.0
g     Monica     yes   17.0
h      Laura      no    NaN
i      Kevin      no    8.5
j     Jordan     yes   19.0

[3-4]

In [76]:
df_0304 = df.groupby('attempts').sum()
df_0304

score
attempts       
1          32.0
2          36.5
3          46.0

[4]

In [78]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Catherine', 'Cahill', 'James', 'Emily', 'Michael', 'Monica', 'Laura', 'Kevin', 'Jordan'],
            'score': [13, 9.5, 16.5, np.nan, 11, 20, 17, np.nan, 8.5, 19],
            'attempts': [1, 3, 3, 2, 2, 3, 2, 3, 2, 1],
            'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a','b','c','d','e','f','g','h','i','j']

exam2_data = {'name': ['Anastasia', 'Catherine', 'Ronaldo', 'James', 'Messi', 'Michael', 'Monica', 'Laura', 'Klassen', 'Jonas'],
             'score2' : [11, 20, 16.5, np.nan, 10, 15, 20, np.nan, 8, 8]}
labels2 = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(exam_data, index=labels)
# print(df)
# print()


df2 = pd.DataFrame(exam2_data, index=labels2)
# print(df2)
# print()

merged_df = df.merge(df2, how="inner", left_index=True, right_index=True)
print(merged_df)


   attempts     name_x qualify  score     name_y  score2
a         1  Anastasia     yes   13.0  Anastasia    11.0
b         3  Catherine      no    9.5  Catherine    20.0
c         3     Cahill     yes   16.5    Ronaldo    16.5
d         2      James      no    NaN      James     NaN
e         2      Emily      no   11.0      Messi    10.0
f         3    Michael     yes   20.0    Michael    15.0
g         2     Monica     yes   17.0     Monica    20.0
h         3      Laura      no    NaN      Laura     NaN
i         2      Kevin      no    8.5    Klassen     8.0
j         1     Jordan     yes   19.0      Jonas     8.0
