## (30) Numpy Module
#### <font color = white>__- Numpy Module은 숫자 data의 large array or matrix 를 다루고, 계산하는데 도움을 주는 Module이다.<br>-Numpy Module 사용하는 방식을 활용해서 scipy Module도 다룰 수 있음__

In [1]:
# Numpy안 쓰고 matrix표현하기

data = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

def sum_matrix(table):
    sum = 0
    for row in range(0, len(table)):
        for col in range(0, len(table[row])):
            sum = sum + table[row][col]
    return sum

sum_matrix(data)

78

***
#### Numpy Array Creation

In [101]:
import numpy as np
a = np.array([1,4,5,8], float) #[1,4,5,8]을 float형식의 array로 만든 것임 / 숫자 형식 default = int임
print(a)
type(a)

[ 1.  4.  5.  8.]


numpy.ndarray

In [7]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]], float)
print(a)
print(a[0,0])
print(a[0,1])

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
1.0
2.0


In [ ]:
import numpy as np
np.array(list)
# np.array(list) : input으로 array형식으로 들어있어야한다.
# np.array(1,2,3,4) WRONG!!!!
# np.array([1,2,3,4]) It's okay!

In [9]:
import numpy as np
#arange -> array range라고 생각하자
print(np.arange(10, 30, 5)) # 10부터 5씩간격을 둔 array를 만드는데 30은 포함안된다 / 범위:[10,30)임
print(np.arange(0, 2, 0.3))

[10 15 20 25]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]


In [1]:
import numpy as np
# numpy.zeros(array_size_tuple) : 0으로 채워진 array를 만들어 준다.
print(np.zeros((3,4)))
print(np.zeros((3)))
print()
#numpy.ones(array_size_tuple) : 1로 채워진 array를 만들어 준다.
print(np.ones((4,3)))
print(np.ones((4)))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[ 0.  0.  0.]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[ 1.  1.  1.  1.]


In [17]:
import numpy as np
# numpy.full(array_size_tuple, value) : 입력한 value로 채워진 array를 size에 맞게 생성함
np.full((5,2), 3)

# numpy.eye(array_size_tuple) : array_size에 맞는 Identity matrix를 생성함
np.eye((5))

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [11]:
import numpy as np

# 질문! random.rand와 random.random을 굳이 나눠서 쓰는 이유가 머지? randn이랑 ranom이랑

# numpy.random.rand(array_size_tuple) : Array filled with normal distribution values
a = np.random.rand(3,3)
#a = np.random.rand(3) = np.random.rand(3)
print(a) # print하면 array라는 표시가 사라짐

# numpy.random.random(array_size_tuple)
a = np.random.random((3,3))
print(a)
np.random.random(3)

[[ 0.36359411  0.18577638  0.57545057]
 [ 0.57105654  0.36309675  0.11648654]
 [ 0.58532555  0.0558317   0.92049407]]
[[ 0.85674418  0.62934975  0.31690884]
 [ 0.62333692  0.68254331  0.12486674]
 [ 0.05921079  0.80101954  0.69226256]]


array([ 0.40029115,  0.35649658,  0.27397836])

In [69]:
import numpy as np

a3 = np.array([[1,2,3],[4,5,6]],float)
a3

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [70]:
import numpy as np

a4 = np.array([1,2,3,'four','five'])
a4

array(['1', '2', '3', 'four', 'five'], 
      dtype='<U11')

In [72]:
print(type(a3))
print(type(a4))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


***
#### Numpy Array Manipulation

1) Array Slicing

In [5]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]], float)
print(a)
print()
print(a[1,:])
print()
print(a[:,2])
print()
print(a[-1:,-2:]) # 뒤에서 1번째 행, 뒤에서 2번째열 선택한 것임
print()
print(a[0:1,0:1])

[[ 1.  2.  3.]
 [ 4.  5.  6.]]

[ 4.  5.  6.]

[ 3.  6.]

[[ 5.  6.]]

[[ 1.]]


2) Transpose an 2D Array

In [84]:
import numpy as np

a = np.array(range(6), float).reshape((2,3)) # 2행 3열로 reshape해줌 reshape안했으면 그냥 1행 6열짜리로 나옴
print(a)
print(a.transpose())

[[ 0.  1.  2.]
 [ 3.  4.  5.]]
[[ 0.  3.]
 [ 1.  4.]
 [ 2.  5.]]


In [85]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]], float)
print(a)
print(a.flatten()) #.flatten은 n차원 행렬을 행벡터로 만들어준다(평평하게 만들어줌)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[ 1.  2.  3.  4.  5.  6.]


In [86]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a,b,c))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

***
#### Numpy Array Mathematics

In [92]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
print(a+b)
print(a-b)
print(a*b) # 단순히 같은 index에 있는 element끼리 곱한다.
print(b/a) # 단순히 같은 index에 있는 element끼리 나눈다.
print(a%b)
print(b**a)

[ 6.  4.  9.]
[-4.  0. -3.]
[  5.   4.  18.]
[ 5.  1.  2.]
[ 1.  0.  3.]
[   5.    4.  216.]


216

In [93]:
import numpy as np
a = [1,2,3,4]
print(a * 2) # list의 곱은 단순히 반복되서 쓰인다

npa = np.array(a)
print(npa * 2) # array의 곱은 각 element들의 곱이 쓰인다.

[1, 2, 3, 4, 1, 2, 3, 4]


array([2, 4, 6, 8])

In [100]:
import numpy as np
a = [1,2,3,4]
b = [1,2,3,4]
print(a+b) # list의 합은 단순히 요소들을 뒤에 이어서 써준다

a = np.array([1,2,3,4], float)
b = np.array([1,2,3,4], float)
print(a+b) # array의 합은 같은 index의 element들을 더해준다

[1, 2, 3, 4, 1, 2, 3, 4]
[ 2.  4.  6.  8.]


Operation in 3D Array

In [102]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b1 = [[1,2,3],[4,5,6],[7,8,9]]
print(a + b1) # list의 합은 단순히 뒤에 이어붙여줌

anp = np.array(a, float)
b1np = np.array(b1, float)
print(anp+b1np)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[  2.   4.   6.]
 [  8.  10.  12.]
 [ 14.  16.  18.]]


***
#### Numpy Array Iteration

In [112]:
import numpy as np

a = np.array([1, 4, 5], int)
for x in a:
    print(x)

1
4
5


In [107]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]], float)
for x in a:
    print(x)

[ 1.  2.]
[ 3.  4.]
[ 5.  6.]


iteration에서 for한번에 1 dimension Iteration이 실행된다.

In [110]:
# 1 dimension iteration

import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
for x in a:
    print(x)
    print('----')

[[1 2 3]
 [4 5 6]]
----
[[ 7  8  9]
 [10 11 12]]
----
[[13 14 15]
 [16 17 18]]
----


In [111]:
# 2 dimension iteration

import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
for x in a:
    for y in x:
        print(y)
        print('----')

[1 2 3]
----
[4 5 6]
----
[7 8 9]
----
[10 11 12]
----
[13 14 15]
----
[16 17 18]
----


***
#### Numpy Array Statistics

1) 일반 계산 

In [114]:
import numpy as np
a = np.array([2, 4, 3], float)
print(a.sum())
a.prod()

24.0

In [116]:
a = np.array([2, 1, 9], float)
print(a.mean())
print(a.var())
print(a.std())

4.0
12.6666666667
3.55902608401


In [10]:
a = np.array([1,4,3,8,9,2,3], float)
np.median(a)
# a.median()은 안된다.

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [118]:
import numpy as np
x = np.array([[1,2],[3,4]])
print(np.sum(x))
# axis = 0은 행, axis = 1은 열을 선택하는 것을 의미한다.
print(np.sum(x, axis = 0))
print(np.sum(x, axis = 1))

10
[4 6]
[3 7]


In [119]:
import numpy as np
npa = np.array([[1,2,3],[4,5,6],[7,8,9]])
npa.sum()


45

In [121]:
# numpy를 안쓰면 이렇게 길게 code를 작성해줘야한다.

def nested_sum(L):
    total = 0
    for i in L:
        if isinstance(i, list):
            total += nested_sum(i)
        else:
            total += i
    return total

a = [[1,2,3],[4,5,6],[7,8,9]]
nested_sum(a)

45

2) Correlation Coefficient / Covariacne
- __<font color = red>공분산은 x가 변하면 y가 어떻게 변하는지 표현해줌.(x,y에 대해서 공통적으로 나타내는 분산)__
- <font color = white>공분산이 양수로 나오면 x, y가 같이 변한다(x가 증가하면 y도 증가)
- 공분산이 음수로 나오면 x, y가 다르게 변한다.(x가 증가하면 y는 감소 / x가 감소하면, y는 증가)<br>
<br>
- __<font color = red>상관계수는 두변수가 얼마나 강한 상관관계가 있는지 알려줌. 공분산을 표준화한 값임.__
- <font color = white>상관계수 r는 항상 부등식 －1≤r≤1을 만족시키며, 양의 상관관계가 있을 때는 r＞0, <br>음의 상관관계가 있을 때는 r＜0이다. 또 무상관일 때는 r＝0이 된다.<br>
<br>
- np.corrcoef(arr) & np.cov(arr)는 2 dimension에서만 가능하다.
- 질문! 어떤게 2dimension? nested가 2번된거 -> 2번 nested된 list는 [x][y] 이렇게 2차원이라 생각하자.

In [125]:
import numpy as np
a = np.array([[1,2,1,3],[5,3,1,8]], float)
c = np.corrcoef(a)
print(c)
np.cov(a) #질문! 공분산이 멀 의미하는거지? (i,i)는 자기 자신의 공분산

[[ 1.          0.72870505]
 [ 0.72870505  1.        ]]


array([[ 0.91666667,  2.08333333],
       [ 2.08333333,  8.91666667]])

3) Dot function for Numpy 1-D Array(Vertor Inner Product)
- (행벡터) x (열벡터) = Single Value
- 위 식에서 x(곱하기)를 Dot이라고도 해서 Dot function임

In [127]:
import numpy as np
a = np.array([1,2,3], float)
b = np.array([0,1,1], float)
#위에처럼 그냥 행벡터를 2개 써준 것이지만 dot()함수를 이용해서 계산 가능
np.dot(a,b)

5.0

4) Matrix Product(Multiplication) = 행렬의 곱(Dot function)
- 행렬의 곱에서의 곱하기도 Dot이라고한다.

Dot function은 1)Vertor Inner Product, 2) Matrix Product(Multiplication)에 쓰인다

In [131]:
a = np.array([[0,1],[2,3]], float)
b = np.array([2,3], float)
c = np.array([[1,1], [4,0]], float)
a
print(np.dot(b,a)) # (1행2열) x (2행 2열) = (1행 2열)
print(np.dot(a,b)) # (2행2열) x (2행 1열) = (1행 2열) ※b는 알아서 변환됨(dot function때문에)
print(np.dot(a,c)) # (2행2열) x (2행 2열) = (2행 2열)
print(np.dot(c,a)) # (1행2열) x (2행 2열) = (1행 2열)

[  6.  11.]
[  3.  13.]
[[  4.   0.]
 [ 14.   2.]]


5) Application of Vector Inner Product
- Matrix의 곱(위에서 보여줌)
- Vector a, b 사이에 있는 각도를 계산
- Vertor Outer Product : Vertor 2개로 Matrix 생성
- Vector Cross Product : Vector a, b로 만들어지는 Area를 계산(평행사변형 그림 기억하자)

In [6]:
a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)
print(np.outer(a, b))
print(np.inner(a, b)) #print(np.dot(a, b))과 같다
print(np.dot(a, b))
print(np.cross(a, b))

[[ 2.  2.  1.]
 [ 8.  8.  4.]
 [ 0.  0.  0.]]
10.0
10.0
[ 4. -1. -6.]


***
#### Numpy Code Example : Nearest Neighbor Search

In [9]:
import numpy as np

# numpy 없이 구하기
points = [[9,2,8],[4,7,2],[3,4,4],[5,6,9],[5,0,7],[8,2,7],[0,3,2],[7,3,0],[6,1,1],[2,9,6]]
qPoint = [4,5,3] #중심이 되는 point?
minIdx = -1
minDist = -1
for idx, point in enumerate(points):
    dist = sum([(dp-dq)**2 for dp, dq in zip(point, qPoint)])**0.5
    print('거리',minDist)
    print(dist)
    if dist < minDist or minDist < 0:
        minDist = dist
        minIdx = idx
print('Nearest point to q: ',points[minIdx] )
print()
# numpy를 활용해서 구하기
points = np.array([[9,2,8],[4,7,2],[3,4,4],[5,6,9],[5,0,7],[8,2,7],[0,3,2],[7,3,0],[6,1,1],[2,9,6]])
qPoint = [4,5,3]
print(points)
print(points - qPoint)
print()
minIdx = np.argmin(np.linalg.norm(points - qPoint, axis=1))
# linalg.norm : linear algebra Matrix or vector norm(||길이||).
# list에서 가장 작은 값의 index를 반환
print('pure numpy Nearest point to q: ', points[minIdx] ) # 질문! 여기에는 왜 ,가 없지?

거리 -1
7.681145747868608
거리 7.681145747868608
2.23606797749979
거리 2.23606797749979
1.7320508075688772
거리 1.7320508075688772
6.164414002968976
거리 1.7320508075688772
6.48074069840786
거리 1.7320508075688772
6.4031242374328485
거리 1.7320508075688772
4.58257569495584
거리 1.7320508075688772
4.69041575982343
거리 1.7320508075688772
4.898979485566356
거리 1.7320508075688772
5.385164807134504
Nearest point to q:  [3, 4, 4]

[[9 2 8]
 [4 7 2]
 [3 4 4]
 [5 6 9]
 [5 0 7]
 [8 2 7]
 [0 3 2]
 [7 3 0]
 [6 1 1]
 [2 9 6]]
[[ 5 -3  5]
 [ 0  2 -1]
 [-1 -1  1]
 [ 1  1  6]
 [ 1 -5  4]
 [ 4 -3  4]
 [-4 -2 -1]
 [ 3 -2 -3]
 [ 2 -4 -2]
 [-2  4  3]]

pure numpy Nearest point to q:  [3 4 4]
